baseURL = "https://coopcreds.com"
languageCode = "en-us"
title = "Co-op Credentials"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  description = 'Credentials to bring co-ops closer together.'
  image = "images/logo/coop-logo.png"
  title = 'Co-op Credentials'
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/coop-logo.png"
    mobile_height = "36px"
    desktop = "images/logo/coop-logo-text.png"
    desktop_height = "36px"
    alt = "Co-op Credentials"

  [params.seo]
    meta_twitter_site = ""
    meta_twitter_creator = ""

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = ""

[menu]
  # Main Menu

  [[menu.main]]
    name = "The Problem"
    url = "/the-problem/"
    weight = 1

  [[menu.main]]
    name = "Our Solution"
    url = "/our-solution/"
    weight = 2

  [[menu.main]]
    name = "Our Work Plan"
    url = "/our-work-plan/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

  [[menu.main]]
    name = "Forum"
    url = "https://community.coopcreds.com"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.footer]]
    name = "Our Problems"
    url = "/our-problems/"
    weight = 2

  [[menu.footer]]
    name = "Our Solution"
    url = "/our-solution/"
    weight = 3

  [[menu.footer]]
    name = "Our Work Plan"
    url = "/our-work-plan/"
    weight = 4

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 5

  [[menu.footer]]
    name = "Forum"
    url = "https://community.coopcreds.com"
    weight = 6
